import './globals.css'
import { Outfit } from "next/font/google"
import { Inter } from "next/font/google"
import { Archivo } from 'next/font/google'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const outfit = Outfit({
  subsets: ['latin'],
  variable: '--font-outfit',
})

const archivo = Archivo({
  subsets: ['latin'],
  variable: '--font-archivo',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${outfit.variable} ${archivo.variable}`}>
      <body>{children}</body>
    </html>
  )
}
